 
     const carModelJson=[{
        model:"Maruti",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Hyundai",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Renault",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Honda",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Tata",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Ford",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"VW",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Mahindra",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Toyota",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"BMW",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       },
       {
        model:"Benz",
        color:"",
        yearofManufacture:"",
        insuranceValidUpto:"",
        kms:"",
        location:"",
        numberOfOwners:"",
        transmission:"",
        externalFitments:"",
        photo:""
       }

    ]

    export default carModelJson